Fix build with Qt-5.15+
linuxdeepin/deepin-deb-installer pull request #15
Opened 2020-12-01 19:02 UTC by openarun

2020-12-04 08:37 UTC, xmuli requested changes

2020-12-04 08:37 UTC, xmuli commented on src/deb_installer/model/packageslistdelegate.cpp
> +
Extra line break

2020-12-04 08:39 UTC, xmuli requested changes
You need to follow this format to submit, otherwise the submission will not be successful.


Please change it, it needs to be submitted in this format, otherwise it will not be successful and bot will automatically -2 and reject it.
[Commit-Information-standard-en](https://github.com/linuxdeepin/developer-center/wiki/Commit-Information-standard-en)  |   [Commit提交规范](https://github.com/linuxdeepin/developer-center/wiki/Commit%E6%8F%90%E4%BA%A4%E8%A7%84%E8%8C%83)

2022-08-10 01:39 UTC, BLumia commented
Sorry for the late reply. We migrated our development workflow back to GitHub, now we can accept PRs, but this patch seems no longer valid on the current codebase. I‘ll close this one for now. If this patch is still valid, please feel free to create a new PR and we will help you get it merged :)

Thanks again for the patch!

2022-08-10 01:39 UTC, closed without merging